apiVersion: apps/v1
kind: Deployment
metadata:
  name: teletype-ingest-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teletype-ingest-service-pod
  template:
    metadata:
      labels:
        app: teletype-ingest-service-pod
    spec:
      containers:
        - image: gcr.io/sab-ors-poc-sbx-01-9096/teletype-ingest-service:latest
          name: teletype-ingest-service
            